sudo: required
services:
    - docker
before_install:
    - docker build -t grhovo/complex-test -f Dockerfile.dev ./client
script:
    - docker run grhovo/complex-test npm test -- --coverage
after_success:
    - docker build -t grhovo/complex-client ./client
    - docker build -t grhovo/complex-nginx ./nginx
    - docker build -t grhovo/complex-server ./server
    - docker build -t grhovo/complex-worker ./worker
    # Log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
    # take these images and push to dockerhub
    - docker push grhovo/complex-client
    - docker push grhovo/complex-nginx
    - docker push grhovo/complex-server
    - docker push grhovo/complex-worker